//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class pli_formData
    {
        public int pli_videoUid { get; set; }
        public int pli_videoUGameServerId { get; set; }
        public string pli_videoGameId { get; set; }
        public string pli_videoUName { get; set; }
        public string pli_videoUNickName { get; set; }
        public string pli_videoPhoneNumber { get; set; }
        public string pli_videoEmail { get; set; }
        public string pli_videoFileCustomName { get; set; }
        public string pli_videoFileContent { get; set; }
        public string pli_videoFileOriName { get; set; }
        public string pli_videoFileNewName { get; set; }
        public string pli_videoFileSize { get; set; }
        public System.DateTime pli_videoFileUploadTime { get; set; }
        public string pli_videoFileUrl { get; set; }
        public int pli_videoIsCheck { get; set; }
        public string pli_videoNotPassContent { get; set; }
        public bool pli_videoMailAlert { get; set; }
        public string pli_videoYoutubelink { get; set; }
    }
}
