//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoApp.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class pli_menuList
    {
        public int pli_mid { get; set; }
        public string pli_MFather { get; set; }
        public string pli_MSon { get; set; }
        public int pli_MGroup { get; set; }
        public int pli_MSort { get; set; }
        public string pli_MLoginType { get; set; }
        public string pli_MUrl { get; set; }
    }
}
